
@host = http://localhost:3000

//
// CATEGORIAS
//

### Get Categorias
GET {{host}}/categorias/ HTTP/1.1

### Get Categoria id = 1
GET {{host}}/categorias/1 HTTP/1.1

### Get Categoria id = 3
GET {{host}}/categorias/comfilmes/3 HTTP/1.1

### Get Categoria id = 99999 (not found test)
GET {{host}}/categorias/9999 HTTP/1.1

### Editar Categoria
PUT {{host}}/categorias/6 HTTP/1.1
content-type: application/json

{
    "nome": "Categoria 6"
}

### Nova Categoria
POST {{host}}/categorias HTTP/1.1
content-type: application/json

{
    "nome": "Categoria 5"
}

### Deletar Categoria
DELETE {{host}}/categorias/2 HTTP/1.1

//
// CLIENTES
//


### Get Clientes
GET {{host}}/clientes/ HTTP/1.1

### Get Cliente id = 1
GET {{host}}/clientes/1 HTTP/1.1

### Get Cliente id = 3
GET {{host}}/clientes/comfilmes/3 HTTP/1.1

### Get Cliente id = 99999 (not found test)
GET {{host}}/clientes/9999 HTTP/1.1

### Editar Cliente
PUT {{host}}/clientes/2 HTTP/1.1
content-type: application/json

{
    "nome": "Cliente 1.1",
    "email": "cliente1",
    "telefone" : "111222"
}

### Nova Cliente
POST {{host}}/clientes HTTP/1.1
content-type: application/json

{
    "nome": "Cliente 1.1",
    "email": "cliente122@gmail.com",
    "telefone" : "111222"
}

### Deletar Cliente
DELETE {{host}}/clientes/2 HTTP/1.1

//
// FILMES
//

### Get Filmes
GET {{host}}/filmes/ HTTP/1.1

### Get Filme id = 1
GET {{host}}/filmes/1 HTTP/1.1

### Get Filme id = 99999 (not found test)
GET {{host}}/filmes/9999 HTTP/1.1

### Editar Filme
PUT {{host}}/filmes/2 HTTP/1.1
content-type: application/json

{
    "nome": "Filme 1.1.1"
    
}

### Novo Filme
POST {{host}}/filmes HTTP/1.1
content-type: application/json

{
    "nome": "Filme 3"
}

### Deletar Filme
DELETE {{host}}/filmes/2 HTTP/1.1
