
@host = {{$dotenv DEV_HOST}}


### Get Filmes
GET {{host}}/filmes/ HTTP/1.1

### Get Filme id = 1
GET {{host}}/filmes/1 HTTP/1.1

### Get Filme id = 99999 (not found test)
GET {{host}}/filmes/9999 HTTP/1.1

### Editar Filme
PUT {{host}}/filmes/2 HTTP/1.1
content-type: application/json

{
    "nome": "Filme 1.1.1"
    
}

### Novo Filme
POST {{host}}/filmes HTTP/1.1
content-type: application/json

{
    "nome": "Filme 3"
}

### Deletar Filme
DELETE {{host}}/filmes/2 HTTP/1.1
